export const DELETE_FORMAT = 'BOOKS/DELETE_FORMAT';
export const DELETE_BOOKS = 'BOOKS/DELETE_BOOKS';
export const UPDATE_BOOK = 'BOOKS/UPDATE';
export const ADD_FORMAT = 'BOOKS/ADD_FORMAT';
export const LOAD_BOOKS = 'BOOKS/LOAD_BOOKS';