export const SET_BOOK_LIST = 'SETTINGS/BOOK_LIST/SET';
export const SET_LIST_VIEW = 'SETTINGS/BOOK_LIST/VIEW';
export const SET_READER = 'SETTINGS/READER/SET';
export const SET_THEME = 'SETTINGS/CONFIG/THEME';