export const XYDOCUMENTATION_URL = 'https://www.xyfir.com/documentation';
export const XYANNOTATIONS_URL = 'http://...';
export const XYACCOUNTS_URL = 'http://...';
export const XYLIBRARY_URL = 'http://...';
export const XYBOOKS_URL = 'http://...';
export const XYFIR_URL = 'http://...';
// export const ENVIRONMENT = 'production';
export const ENVIRONMENT = 'development';
export const LOG_STATE = true;
