export const ACCOUNT = "ACCOUNT";
export const PURCHASE_SUBSCRIPTION = "ACCOUNT/PURCHASE_SUBSCRIPTION";

export const READ_BOOK = "BOOKS/READ";
export const UPLOAD_BOOKS = "BOOKS/UPLOAD";
export const SEARCH_BOOKS = "BOOKS/SEARCH";
export const EDIT_METADATA = "BOOKS/METADATA";

export const LIST_TAGS = "BOOKS/LIST/TAGS";
export const LIST_BOOKS = "BOOKS/LIST/ALL";
export const LIST_SERIES = "BOOKS/LIST/SERIES";
export const LIST_RATINGS = "BOOKS/LIST/RATINGS";
export const LIST_AUTHORS = "BOOKS/LIST/AUTHORS";
export const LIST_AUTHOR_SORT = "BOOKS/LIST/AUTHOR_SORT";

export const LIST_BY_ALL = "BOOKS/LIST/BY/ALL";
export const LIST_BY_TAG = "BOOKS/LIST/BY/TAG";
export const LIST_BY_RATING = "BOOKS/LIST/BY/RATING";
export const LIST_BY_SERIES = "BOOKS/LIST/BY/SERIES";
export const LIST_BY_AUTHORS = "BOOKS/LIST/BY/AUTHORS";
export const LIST_BY_AUTHOR_SORT = "BOOKS/LIST/BY/AUTHOR_SORT";

export const LIBRARY_INFO = "LIBRARY/INFO";
export const LIBRARY_UPLOAD = "LIBRARY/UPLOAD";
export const LIBRARY_DOWNLOAD = "LIBRARY/DOWNLOAD";