export const ACCOUNT = 'ACCOUNT';
export const EXTEND_SUBSCRIPTION = 'ACCOUNT/PURCHASE/EXTEND_SUB';
export const INCREASE_SIZE_LIMIT = 'ACCOUNT/PURCHASE/INCREASE_SIZE_LIMIT';
export const PURCHASE_SUBSCRIPTION = 'ACCOUNT/PURCHASE/SUBSCRIPTION';
export const XYANNOTATIONS_PURCHASE = 'ACCOUNT/PURCHASE/XYANNOTATIONS';

export const READ_BOOK = 'BOOKS/READ';
export const BULK_EDIT = 'BOOKS/BULK_EDIT';
export const ADD_FORMAT = 'BOOKS/ADD_FORMAT';
export const MANAGE_BOOK = 'BOOKS/MANAGE';
export const UPLOAD_BOOKS = 'BOOKS/UPLOAD';
export const RECENTLY_OPENED = 'BOOKS/RECENTLY_OPENED';

export const LIST_TAGS = 'BOOKS/LIST/TAGS';
export const LIST_BOOKS = 'BOOKS/LIST/ALL';
export const LIST_SERIES = 'BOOKS/LIST/SERIES';
export const LIST_RATINGS = 'BOOKS/LIST/RATINGS';
export const LIST_AUTHORS = 'BOOKS/LIST/AUTHORS';
export const LIST_AUTHOR_SORT = 'BOOKS/LIST/AUTHOR_SORT';

export const LIBRARY_INFO = 'LIBRARY/INFO';
export const LIBRARY_UPLOAD = 'LIBRARY/UPLOAD';
export const LIBRARY_DOWNLOAD = 'LIBRARY/DOWNLOAD';

export const READER_SETTINGS = 'SETTINGS/READER';
export const GENERAL_SETTINGS = 'SETTINGS/GENERAL';
export const BOOK_LIST_SETTINGS = 'SETTINGS/BOOK_LIST';
