export const SET_LIBRARY_SIZE_LIMIT = 'ACCOUNT/SET_LIBRARY_SIZE_LIMIT';
export const PURCHASE_SUBSCRIPTION = 'ACCOUNT/PURCHASE_SUBSCRIPTION';
export const SET_XYANNOTATIONS_KEY = 'ACCOUNT/SET_XYANNOTATIONS_KEY';